name: release

on:
  push:
    branches:
      - master

# Definiujemy pełne uprawnienia zapisu dla kodu i tagów dla bota GitHub Actions
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Bezpieczne nadanie taga lokalnie i przekazanie go do środowiska GoReleaser
      - name: Create Automatic Tag
        run: |
          COMMITS_COUNT=$(git rev-list --count HEAD)
          TAG_NAME="v0.1.${COMMITS_COUNT}"
          echo "Generowanie automatycznej wersji: $TAG_NAME"
          
          # Konfiguracja tożsamości bota
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Nadajemy tag tylko lokalnie wewnątrz maszyny wirtualnej,
          # aby GoReleaser go widział bez konieczności robienia problematycznego "git push"
          git tag $TAG_NAME

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          # Flaga --snapshot pozwala GoReleaserowi zbudować oficjalne pliki
          # na podstawie lokalnego taga, ignorując brak taga na zdalnym serwerze
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
