name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Ten krok tworzy tag i WYPYCHA go na serwer, co aktywuje mechanizm Release
      - name: Create and Push Automatic Tag
        run: |
          COMMITS_COUNT=$(git rev-list --count HEAD)
          TAG_NAME="v0.1.${COMMITS_COUNT}"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git tag $TAG_NAME
          git push origin $TAG_NAME # Wypchnięcie taga na serwer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # GoReleaser bez flagi snapshot automatycznie stworzy oficjalny wpis w zakładce Releases
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
